from telebot import types

def KEYBOARD_NAMES_TASKS(message):
    kb = types.InlineKeyboardMarkup()

    name_1 = types.InlineKeyboardButton(text='Задание 1', callback_data='names_tasks: 0')
    name_2 = types.InlineKeyboardButton(text='Задание 2', callback_data='names_tasks: 1')
    name_3 = types.InlineKeyboardButton(text='Задание 3', callback_data='names_tasks: 2')
    name_4 = types.InlineKeyboardButton(text='Задание 4', callback_data='names_tasks: 3')
    name_5 = types.InlineKeyboardButton(text='Задание 5', callback_data='names_tasks: 4')
    name_6 = types.InlineKeyboardButton(text='Задание 6', callback_data='names_tasks: 5')
    name_7 = types.InlineKeyboardButton(text='Задание 7', callback_data='names_tasks: 6')
    name_8 = types.InlineKeyboardButton(text='Задание 8', callback_data='names_tasks: 7')
    name_9 = types.InlineKeyboardButton(text='Задание 9', callback_data='names_tasks: 8')
    name_10 = types.InlineKeyboardButton(text='Задание 10', callback_data='names_tasks: 9')
    name_11 = types.InlineKeyboardButton(text='Задание 11', callback_data='names_tasks: 10')
    name_12 = types.InlineKeyboardButton(text='Задание 12', callback_data='names_tasks: 11')
    name_13 = types.InlineKeyboardButton(text='Задание 13', callback_data='names_tasks: 12')
    name_14 = types.InlineKeyboardButton(text='Задание 14', callback_data='names_tasks: 13')
    name_15 = types.InlineKeyboardButton(text='Задание 15', callback_data='names_tasks: 14')
    name_16 = types.InlineKeyboardButton(text='Задание 16', callback_data='names_tasks: 15')
    name_17 = types.InlineKeyboardButton(text='Задание 17', callback_data='names_tasks: 16')
    name_18 = types.InlineKeyboardButton(text='Задание 18', callback_data='names_tasks: 17')
    name_19 = types.InlineKeyboardButton(text='Задание 19', callback_data='names_tasks: 18')
    name_20 = types.InlineKeyboardButton(text='Задание 20', callback_data='names_tasks: 19')
    name_21 = types.InlineKeyboardButton(text='Задание 21', callback_data='names_tasks: 20')
    name_22 = types.InlineKeyboardButton(text='Задание 22', callback_data='names_tasks: 21')
    name_23 = types.InlineKeyboardButton(text='Задание 23', callback_data='names_tasks: 22')
    name_24 = types.InlineKeyboardButton(text='Задание 24', callback_data='names_tasks: 23')
    name_25 = types.InlineKeyboardButton(text='Задание 25', callback_data='names_tasks: 24')
    name_26 = types.InlineKeyboardButton(text='Задание 26', callback_data='names_tasks: 25')
    name_27 = types.InlineKeyboardButton(text='Задание 27', callback_data='names_tasks: 26')
    name_28 = types.InlineKeyboardButton(text='Задание 28', callback_data='names_tasks: 27')
    name_29 = types.InlineKeyboardButton(text='Задание 29', callback_data='names_tasks: 28')
    name_30 = types.InlineKeyboardButton(text='Задание 30', callback_data='names_tasks: 29')
    name_31 = types.InlineKeyboardButton(text='Задание 31', callback_data='names_tasks: 30')
    name_32 = types.InlineKeyboardButton(text='Задание 32', callback_data='names_tasks: 31')
    name_33 = types.InlineKeyboardButton(text='Задание 33', callback_data='names_tasks: 32')
    name_34 = types.InlineKeyboardButton(text='Задание 34', callback_data='names_tasks: 33')
    name_35 = types.InlineKeyboardButton(text='Задание 35', callback_data='names_tasks: 34')
    name_36 = types.InlineKeyboardButton(text='Задание 36', callback_data='names_tasks: 35')
    name_37 = types.InlineKeyboardButton(text='Задание 37', callback_data='names_tasks: 36')
    name_38 = types.InlineKeyboardButton(text='Задание 38', callback_data='names_tasks: 37')
    name_39 = types.InlineKeyboardButton(text='Задание 39', callback_data='names_tasks: 38')
    name_40 = types.InlineKeyboardButton(text='Задание 40', callback_data='names_tasks: 39')
    name_41 = types.InlineKeyboardButton(text='Задание 41', callback_data='names_tasks: 40')
    name_42 = types.InlineKeyboardButton(text='Задание 42', callback_data='names_tasks: 41')
    name_43 = types.InlineKeyboardButton(text='Задание 43', callback_data='names_tasks: 42')
    name_44 = types.InlineKeyboardButton(text='Задание 44', callback_data='names_tasks: 43')
    name_45 = types.InlineKeyboardButton(text='Задание 45', callback_data='names_tasks: 44')
    name_46 = types.InlineKeyboardButton(text='Задание 46', callback_data='names_tasks: 45')
    name_47 = types.InlineKeyboardButton(text='Задание 47', callback_data='names_tasks: 46')
    name_48 = types.InlineKeyboardButton(text='Задание 48', callback_data='names_tasks: 47')
    name_49 = types.InlineKeyboardButton(text='Задание 49', callback_data='names_tasks: 48')
    name_50 = types.InlineKeyboardButton(text='Задание 50', callback_data='names_tasks: 49')
    name_51 = types.InlineKeyboardButton(text='Задание 51', callback_data='names_tasks: 50')
    name_52 = types.InlineKeyboardButton(text='Задание 52', callback_data='names_tasks: 51')
    name_53 = types.InlineKeyboardButton(text='Задание 53', callback_data='names_tasks: 52')
    name_54 = types.InlineKeyboardButton(text='Задание 54', callback_data='names_tasks: 53')
    name_55 = types.InlineKeyboardButton(text='Задание 55', callback_data='names_tasks: 54')
    name_56 = types.InlineKeyboardButton(text='Задание 56', callback_data='names_tasks: 55')
    name_57 = types.InlineKeyboardButton(text='Задание 57', callback_data='names_tasks: 56')
    name_58 = types.InlineKeyboardButton(text='Задание 58', callback_data='names_tasks: 57')
    name_59 = types.InlineKeyboardButton(text='Задание 59', callback_data='names_tasks: 58')
    name_60 = types.InlineKeyboardButton(text='Задание 60', callback_data='names_tasks: 59')

    kb.add(name_1, name_2, name_3, name_4, name_5, name_6, name_7, name_8, name_9, name_10,
           name_11, name_12, name_13, name_14, name_15, name_16, name_17, name_18, name_19, name_20,
           name_21, name_22, name_23, name_24, name_25, name_26, name_27, name_28, name_29, name_30,
           name_31, name_32, name_33, name_34, name_35, name_36, name_37, name_38, name_39, name_40,
           name_41, name_42, name_43, name_44, name_45, name_46, name_47, name_48, name_49, name_50,
           name_51, name_52, name_53, name_54, name_55, name_56, name_57, name_58, name_59, name_60)
    return(kb)